name = "RDataGet"
uuid = "a115732e-4334-4ecb-8ea3-f683e7f66d4d"
authors = ["Frankie Robertson <frankie@robertson.name> and contributors"]
version = "0.1.0"

[deps]
Arrow = "69666777-d1a9-59fb-9406-91d4454c9d45"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CodecBzip2 = "523fee87-0ab8-5b00-afb7-3ecf72e48cfd"
CodecXz = "ba30903b-d9e8-5048-a5ec-d1f5b0d4b47b"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
FileTypes = "b58e86d0-4a47-4fce-a54d-8006a143ed90"
OhMyArtifacts = "cf8be1f4-309d-442e-839d-29d2a0af6cb7"
RData = "df47a6cb-8c03-5eed-afd8-b6050d6c41da"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Tar = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"
UrlDownload = "856ac37a-3032-4c1c-9122-f86d88358c8b"

[compat]
CSV = "0.10"
CodecBzip2 = "0.8"
CodecXz = "0.7"
CodecZlib = "0.7"
DataFrames = "1"
FileTypes = "0.1.0"
RData = "0.8, 1"
Reexport = "1"
Tables = "1.12.1"
UrlDownload = "1"
julia = "1.12"

[workspace]
projects = ["docs", "test"]
